# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: ja-JP
reviews:
  profile: "chill"
  high_level_summary: true
  poem: false
  auto_review:
    drafts: false
    ignore_title_keywords:
      - "WIP"
  path_instructions:
    - path: "**/*.swift"
      instructions: >
        Swift API Design Guidelinesに従っているか確認してください。
        CLAUDE.mdのコミット規約・コード規約に沿っているかもチェックしてください。
